# Minimal numpy stub shim — Python 3.11-compatible syntax.
#
# NumPy 2.x bundles stubs that use PEP 695 `type X = Y` syntax (Python 3.12+),
# which mypy cannot parse when python_version = "3.11".  This shim is placed
# under stubs/ (ahead of site-packages on mypy_path) so mypy picks it up first.
# All numpy symbols are typed as Any; numpy-specific correctness is validated
# at runtime and by OpenCV/our own tests.  The imaging module's own explicit
# type annotations are still fully checked.
from __future__ import annotations

from typing import Any

class ndarray:
    shape: tuple[int, ...]
    dtype: Any
    ndim: int
    size: int
    flat: Any
    T: ndarray

    def __getattr__(self, name: str) -> Any: ...
    def __setattr__(self, name: str, value: Any) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Any: ...
    def __getitem__(self, key: Any) -> Any: ...
    def __setitem__(self, key: Any, value: Any) -> None: ...
    def __bool__(self) -> bool: ...
    def __add__(self, other: Any) -> ndarray: ...
    def __sub__(self, other: Any) -> ndarray: ...
    def __mul__(self, other: Any) -> ndarray: ...
    def __truediv__(self, other: Any) -> ndarray: ...
    def __lt__(self, other: Any) -> ndarray: ...
    def __le__(self, other: Any) -> ndarray: ...
    def __gt__(self, other: Any) -> ndarray: ...
    def __ge__(self, other: Any) -> ndarray: ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
    def __invert__(self) -> ndarray: ...
    def __pow__(self, other: Any) -> ndarray: ...
    def astype(self, dtype: Any, **kw: Any) -> ndarray: ...
    def reshape(self, *args: Any) -> ndarray: ...
    def copy(self) -> ndarray: ...
    def tolist(self) -> Any: ...
    def tobytes(self) -> bytes: ...
    def mean(self, **kw: Any) -> Any: ...
    def sum(self, **kw: Any) -> Any: ...
    def max(self, **kw: Any) -> Any: ...
    def min(self, **kw: Any) -> Any: ...
    def argmax(self, **kw: Any) -> Any: ...
    def argmin(self, **kw: Any) -> Any: ...
    def argsort(self, **kw: Any) -> ndarray: ...
    def any(self) -> bool: ...
    def all(self) -> bool: ...
    def flatten(self) -> ndarray: ...


# Scalar dtypes exposed as constructors / type markers
uint8: Any
uint16: Any
uint32: Any
int16: Any
int32: Any
int64: Any
float32: Any
float64: Any
bool_: Any

# Module-level True / False sentinels
True_: Any
False_: Any

def __getattr__(name: str) -> Any: ...
